### ISSUE TITLE
Centering animated gif

### ISSUE THREAD

**Issue by larryslater** [krasimir/gifffer#14]
Great plugin but when I try to center the gif in a div is defaults to align: left.

How can I center the gif?

Thank!

**Comment by krasimir** [comment]
Hey, the aligning of the image is a little bit out of the scope of this library. Can you please post your markup and how you tried center it (probably the CSS).

**Comment by larryslater** [comment]
Hey Krashimir;

I'm using some responsive code and that may be messing things up. I'm
working on it but thanks a lot for your quick reply.

Larry

Larry Slater

**Comment by larryslater** [comment]
Krashimir;

I found that this works for centering the block element:

.center {margin-left:auto;margin-right:auto;width:XXXpx;height:XXXpx;}

I hope this helps others.

Thanks so much for this GREAT plugin!

**Comment by krasimir** [comment]
👍
