### ISSUE TITLE
Not accessible

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [krasimir/gifffer#15]
- Step 1: change [container](https://github.com/krasimir/gifffer/blob/master/lib/gifffer.js#L28) div to button to allow keyboard access.  
- Step 2: add possibility to add visibly hidden alt-text for screen reader users.  

Is this a welcomed contribution?

**Comment by krasimir** [comment]
The `<button>` suggestion is a nice one and I made that change (`1.2.1` version released). I'm  a little bit puzzled about the second step. Can you please clarify on that.

**Comment by ThibaultJanBeyer** [comment]
right, so normal images have an "alt" Attribute. See `<img src="img.gif" alt="some text">`, if a blind user traverse the page, his screen reader will read aloud that alt attribute: 'some text, img'. Now with gifffer we lose that alt attribute. An Idea would be to have something like this: `<img data-gifffer="image.gif" data-gifffer-alt="some text" />` and using that information in code to populate the gifffer with a visually hidden text. Simplified something like this: `<container><playbutton /><canvas />some text</container>` so that some text remains there. Then, it actually makes more sense to make the playbutton a button, not the whole div and hide the playbutton for screen readers (since blind users do not need to play the gif, they just need access to the alt text). Which is also a good practice for SEO… I would love to make a pull request this weekend with that addition, what do you think?

**Comment by krasimir** [comment]
I see. The `container-to-button` is already done. I'll be happy to see a PR for the `alt` text.

**Comment by ThibaultJanBeyer** [comment]
You may close this issue now 👍
