### ISSUE TITLE
Can you apply the play/stop button on a frame other than the 1st? 

### ISSUE THREAD

**Issue by ilacorda** [krasimir/gifffer#19]
Hi,
I am trying to have the animated gif stopped not on the first frame, but on the 3rd, is that possible?

**Comment by krasimir** [comment]
Hey, sorry that's currently not possible with Gifffer because he library is not working with the frames of the gif

**Comment by ilacorda** [comment]
Hi, thank you for your reply, very much appreciated. My understanding is that gifffer makes a screenshot of one of the first frames and replaces the original tag with a <div> element. Is that correct? I wonder whether there a way to apply some delay, but it seems that this cannot be done.

**Comment by krasimir** [comment]
> My understanding is that gifffer makes a screenshot of one of the first frames and replaces the original tag

Yep, that's the case. However, this behavior is not consistent. Sometimes we get a screenshot of the second frame or the third one. I see some relation with the size of the gif + that behavior depends on the browser. So, the idea with the delay is interesting but I doubt that we can achieve stability here.

I'll close this issue for now. Let me know if you find a solution for your case.

**Comment by ilacorda** [comment]
Thanks krasimir,
I have been successfully using some slightly modified version of gifffer on production and it works as expected. Great project, thank you for all your help!
