### ISSUE TITLE
Customization request

### ISSUE THREAD

**Issue by Jogai** [krasimir/gifffer#21]
Works well, but I have some darker images and the play button is barely visible. Would it be possbile to adjust the constructor to take some (optional) parameters? For me it would fit a lot better if I can set size & colors.

note: the click to play button on flash elements in chrome are 50px by default 😉

**Comment by krasimir** [comment]
@Jogai it's done. A new version 1.5.0 is released. Check out the docs https://github.com/krasimir/gifffer#styling

**Comment by Jogai** [comment]
Ah wow, thanks for the fast response!

**Comment by krasimir** [comment]
You are welcome :)
