### ISSUE TITLE
the problem of calculatePercentageDim 

### ISSUE THREAD

**Issue by phoenix-yassin** [krasimir/gifffer#26]
`function calculatePercentageDim (el, w, h, wOrig, hOrig) {
  var parentDimW = el.parentNode.offsetWidth;
  var parentDimH = el.parentNode.offsetHeight;
  var ratio = wOrig / hOrig;

  if (w.toString().indexOf('%') > 0) {
    w = parseInt(w.toString().replace('%', ''));
    w = (w / 100) * parentDimW;
    h = w / ratio;
  } else if (h.toString().indexOf('%') > 0) {
    h = parseInt(h.toString().replace('%', ''));
    h = (h / 100) * parentDimW;
    w = h / ratio;
  }

  return { w: w, h: h };
};`

in the block 'else if', w & h is calculated in a flawed way!
Maybe as below:

`else if (h.toString().indexOf('%') > 0) {
    h = parseInt(h.toString().replace('%', ''));
    h = (h / 100) * parentDimH;
    w = h * ratio;
  }`

**Comment by krasimir** [comment]
Yep, you are right. It's fixed and released as `1.5.1` version. Thanks.
