### ISSUE TITLE
Width and height percentage support needed.

### ISSUE THREAD

**Issue by Venediktoff** [krasimir/gifffer#3]
You can't specify height and width in percents which would be a big advantage!

**Comment by krasimir** [comment]
Hi, the library uses [drawImage](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D.drawImage) and I'm 90% sure that can not work with percents. I think it accepts only pixels.

**Comment by Venediktoff** [comment]
But it gives you a weird effect if you only specify width. Have a look at this: http://writinger.com/tag/lol/ if I just load the page, I get a playable gif with specified width and gif's standard height, but if I refresh the page it takes a normal size. Any comments on this bug (or maybe not bug). That's why I was wondering about percents.

**Comment by Venediktoff** [comment]
But it gives you a weird effect if you only specify width. Have a look at this: http://writinger.com/tag/lol/ if I just load the page, I get a playable gif with specified width and gif's standard height, but if I refresh the page it takes a normal size. Any comments on this bug (or maybe not bug). That's why I was wondering about percents.

**Comment by Venediktoff** [comment]
But it gives you a weird effect if you only specify width. Have a look at this: http://writinger.com/tag/lol/ if I just load the page, I get a playable gif with specified width and gif's standard height, but if I refresh the page it takes a normal size. Any comments on this bug (or maybe not bug). That's why I was wondering about percents.

**Comment by krasimir** [comment]
A year later :)

Gifffer now accepts percentages as width. Feel free to download the latest version https://github.com/krasimir/gifffer/tree/master/build

**Comment by dellert** [comment]
Strange, but percentage not working/ I set  data-gifffer-width="100%", and your script sets 0px width and height to gif element

**Comment by krasimir** [comment]
Can you please provide an example. I mean a page where it doesn't work.

**Comment by dellert** [comment]
`<img data-gifffer="<?php echo $value ?>" data-gifffer-width="100%">`
I cannot give you link to page. I develop on my local vagrant machine

**Comment by krasimir** [comment]
@dellert one last thing. Your browser, OS and versions.

**Comment by dellert** [comment]
Chrome 48, Windows 8.1, last version this plugin

**Comment by krasimir** [comment]
@dellert is the percentage example on this page working on your machine http://krasimir.github.io/gifffer/

I made some tests and as long as the parent container has a width higher then 0 using `100%` should work. Can you confirm that the element which is containing your image has a width > 0.

**Comment by dellert** [comment]
Even I force set style width for outer element, nothing happens.
I need percentage declaration for adaptive page view

**Comment by krasimir** [comment]
I'm not able to reproduce the problem right now. Can you please create a jsbin or jsfiddle. The link to the library is http://krasimir.github.io/gifffer/lib/gifffer.js
