### ISSUE TITLE
Showing last played frame when pause button pressed

### ISSUE THREAD

**Issue by demola-d** [krasimir/gifffer#33]
Hi krasimir,

firstly thanks! for the awesome library, works like a charm and really easy to get up and going.
Would it be possible to modify the javascript so that the last played frame is displayed in the pause state, rather than the initial one?

Thanks
Dave

**Comment by krasimir** [comment]
Hey, I already tried that some time ago. Unfortunately that's not possible with the approach which the library is using.

**Comment by demola-d** [comment]
Ah, I thought that might be the case, as it was a pretty obvious feature to try!
But nonetheless thanks for the useful tool :)
