### ISSUE TITLE
Node module won't resolve

### ISSUE THREAD

**Issue by patosullivan** [krasimir/gifffer#34]
After updating from 1.5.1 to 1.5.3 via `npm update` I can no longer import Gifffer from my node_modules folder using the normal syntax, e.g.:

`import Gifffer from "gifffer"`

Webpack will report:

`Module not found: Error: Can't resolve 'gifffer' in [file]`

I am working around this temporarily by downgrading to 1.5.1.

**Comment by killianjimenez** [comment]
same here. But downgrading to 1.5.1 did not work for me... did you do anything else besides that?

**Comment by vt-rli** [comment]
Check the package.json file of the v1.5.3
The `"main"` value is `"build/gifffer.js"`, but it cannot find this file under `build` folder.

So you can figure it out by either option:
1. Update the `"main"` value in `package.json`;
2. Rename the `"build/gifffer.min.js"` to `"build/gifffer.js"`;

**Comment by krasimir** [comment]
Thanks. Fixed. I deployed a new minor release containing your fix.
