### ISSUE TITLE
Minor things: automatic width, running Gifffer() many times

### ISSUE THREAD

**Issue by kajmagnus** [krasimir/gifffer#4]
Hi Krasimir,

Gifffer works great for me :-) I've made some tweaks in my copy of Gifffer, perhaps you'd like to have a look in case there's something you'd like to incorporate in your master version.

https://github.com/debiki/debiki-server/blob/master/client/third-party/gifffer/gifffer.js

Here's the diff of my changes:  https://github.com/debiki/debiki-server/commit/7ae26019bdea4c8edc6946adc9d17734ab9f7d48 (search for `gifffer.js` on that diff page)

There are two changes that might be of interest:

- Make `Gifffer()` safe to run many times (in my case, more gifs are sometimes added long after page load)
- Scale gifs so they fit in the parent elem: `max-width: 100%`. And reposition the play button via CSS `calc(50% + ...)` so it's always in the middle, regardless of the current gif size

( + tweak colors. I thought the play button was a bit too transparent.)

(There are some other changes as well but I think they are specific for my web app.)

**Comment by krasimir** [comment]
@kajmagnus thanks for the update. I like the changes. Can you please prepare a pull request.

**Comment by kajmagnus** [comment]
Hi krasimir, Thanks for the feedback. I'm not sure when I'll have time to prepare a PR — I'm currently working a lot with trying to make a hobby project usable. (Also I feel I ought to test that the PR works for other people than me, but ... I don't know how people typically use Gifffer)

**Comment by krasimir** [comment]
To be honest I don't know how many people are using Gifffer. I'm not even sure if someone is using it :)

**Comment by PunKeel** [comment]
I'm using it ! :heart:

**Comment by krasimir** [comment]
@kajmagnus closing this one. Please reopen as pull request. I like your changes.
