### ISSUE TITLE
Option to set preview frame image and avoid loading image until clicked on?

### ISSUE THREAD

**Issue by jasondavis** [krasimir/gifffer#5]
I would like to use something like this on a page with many GIFs so I need a way to have my GIFs downloaded only once clicked on instead of all loaded on page load.  If I have 100mb of GIFs on the page, the point of having a play button for me is to allow for the page to still be fast but currently it downloads all images on page load to get the first frame image for preview.
Any chance of modifying to make it optional to provide a URL of preview image and have it only download image on demand when play is clicked?

**Comment by krasimir** [comment]
Well, Gifffer is [based](https://github.com/krasimir/gifffer/blob/master/lib/gifffer.js#L33) on `onload` event of the images. Without that we can't create the preview. I guess you should go with the old-fashion way of:
* generating preview of the give on the server and load that instead
* load a static image placeholder and write some JavaScript that loads progressively all the gifs
