### ISSUE TITLE
weird behaviour in internet explorer 11

### ISSUE THREAD

**Issue by babautz** [krasimir/gifffer#7]
Hello,

I really like gifffer, but the behaviour of gifs in internet explorer is a bit weird.

What I want: 
A gif, that gets played onclick and stops after a while (or on click again). If you decide to play the gif again, it starts with the first frame. This works, as shown in your examples, in firefox, opera and chrome. However In internet explorer the gif starts with the last shown frame. This is not a huge issue, but its annoying. Is there any way around this behaviour?

thanks in advance

**Comment by krasimir** [comment]
Hello, @babautz 

What version of IE you are testing on?

**Comment by babautz** [comment]
11.0.9600.18124 (Windows 7), Update-Version 11.0.26

**Comment by krasimir** [comment]
Ok, @babautz I'll try testing under IE11 and will write here why is working differently.

**Comment by krasimir** [comment]
I just tested in all the browsers that I have on my machine and they all work the same way. The gif starts from the beginning when you stop it. The library replaces `<img>` tags so there is no actual frame-by-frame gif animation. Sorry @babautz but your issue can't be solved with gifffer or at least not with the approach that it takes. Here are few other libraries that may help:

https://github.com/rfrench/gify
https://github.com/buzzfeed/libgif-js
