### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by HardeepAsrani** [krasimir/gifffer#9]
I made the max-width 100% but when I switch screen from normal to landscape, canvas doesn't resize. It loads just fine, regardless of screensize, but on screen resize it's not responsive.

**Comment by krasimir** [comment]
Giffer uses canvas to draw the image and the `<canvas>` tag [requires](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas) fixed CSS pixel values of its `width` and `height` attributes. So to make the canvas responsive we have to redraw it on every layout change which may be really expensive. 

A quick solution may be to flush the content of your container add the same tag and call `Gifffer();` one more time. But that also involves a detection of orientation change.

**Comment by ThibaultJanBeyer** [comment]
What about adding css with & height values after it has been drawn? (100% on the canvas and the respective user choice on the container) Made a quick test, worked fine. Would that be a welcomed contribution?

**Comment by krasimir** [comment]
@ThibaultJanBeyer I would love to see a PR for that but as far as I know we need JavaScript to achieve responsiveness of a canvas. Can you please give me an example of how 100% of the canvas's width and height work.

**Comment by ThibaultJanBeyer** [comment]
Alright, I’ll get to code tomorrow probably, expect the pr to come :)

**Comment by meceware** [comment]
Hey,

I removed the width and height of `con` sets in the click event and set the style as
```
con.setAttribute('style', 'position:relative;cursor:pointer;width:100%;height:100%;background:none;border:none;padding:0;');
```

Since it sets the width and height as 100%, the parent element can give the width and height. I think it can be done via CSS.
